export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";

export const ADD_PHONE_TO_TO_ADDRESS = "ADD_PHONE_TO_TO_ADDRESS";
export const ADD_NAME_TO_TO_ADDRESS = "ADD_NAME_TO_TO_ADDRESS";
export const ADD_COMPANY_TO_TO_ADDRESS = "ADD_COMPANY_TO_TO_ADDRESS";
export const ADD_COUNTRY_TO_TO_ADDRESS = "ADD_COUNTRY_TO_TO_ADDRESS";
export const ADD_ADDRESS1_TO_TO_ADDRESS = "ADD_ADDRESS1_TO_TO_ADDRESS";
export const ADD_ADDRESS2_TO_TO_ADDRESS = "ADD_ADDRESS2_TO_TO_ADDRESS";
export const ADD_ADDRESS3_TO_TO_ADDRESS = "ADD_ADDRESS3_TO_TO_ADDRESS";
export const ADD_CITY_TO_TO_ADDRESS = "ADD_CITY_TO_TO_ADDRESS";
export const ADD_STATE_TO_TO_ADDRESS = "ADD_STATE_TO_TO_ADDRESS";
export const ADD_EMAIL_TO_TO_ADDRESS = "ADD_EMAIL_TO_TO_ADDRESS";
export const CLEAR_TO_ADDRESS = "CLEAR_TO_ADDRESS";

export const ADD_PHONE_TO_FROM_ADDRESS = "ADD_PHONE_TO_FROM_ADDRESS";
export const ADD_NAME_TO_FROM_ADDRESS = "ADD_NAME_TO_FROM_ADDRESS";
export const ADD_COMPANY_TO_FROM_ADDRESS = "ADD_COMPANY_TO_FROM_ADDRESS";
export const ADD_COUNTRY_TO_FROM_ADDRESS = "ADD_COUNTRY_TO_FROM_ADDRESS";
export const ADD_ADDRESS1_TO_FROM_ADDRESS = "ADD_ADDRESS1_TO_FROM_ADDRESS";
export const ADD_ADDRESS2_TO_FROM_ADDRESS = "ADD_ADDRESS2_TO_FROM_ADDRESS";
export const ADD_ADDRESS3_TO_FROM_ADDRESS = "ADD_ADDRESS3_TO_FROM_ADDRESS";
export const ADD_CITY_TO_FROM_ADDRESS = "ADD_CITY_TO_FROM_ADDRESS";
export const ADD_STATE_TO_FROM_ADDRESS = "ADD_STATE_TO_FROM_ADDRESS";
export const ADD_EMAIL_TO_FROM_ADDRESS = "ADD_EMAIL_TO_FROM_ADDRESS";
export const CLEAR_FROM_ADDRESS = "CLEAR_FROM_ADDRESS";

export const SWITCH_ADDRESS = "SWITCH_ADDRESS";
export const NEXT_ON_CREATE_ADDRESS = "NEXT_ON_CREATE_ADDRESS";
export const CLEAR_CREATE_ADDRESS = "CLEAR_CREATE_ADDRESS";

export const SHOW_CREATE_ADDRESS = "SHOW_CREATE_ADDRESS";
export const HIDE_CREATE_ADDRESS = "HIDE_CREATE_ADDRESS";
export const SHOW_CREATE_SHIP_DETAILS = "SHOW_CREATE_SHIP_DETAILS";
export const HIDE_CREATE_SHIP_DETAILS = "HIDE_CREATE_SHIP_DETAILS";

export const OPEN_PROTECT_MODAL = "OPEN_PROTECT_MODAL";
export const OPEN_PROHIBIT_MODAL = "OPEN_PROHIBIT_MODAL";
export const OPEN_DOCPACK_MODAL = "OPEN_DOCPACK_MODAL";

export const CLOSE_PROTECT_MODAL = "CLOSE_PROTECT_MODAL";
export const CLOSE_PROHIBIT_MODAL = "CLOSE_PROHIBIT_MODAL";
export const CLOSE_DOCPACK_MODAL = "CLOSE_DOCPACK_MODAL";

export const SET_SHIPMENT_TYPE_TO_DOC = "SET_SHIPMENT_TYPE_TO_DOC";
export const SET_SHIPMENT_TYPE_TO_PACK = "SET_SHIPMENT_TYPE_TO_PACK";

export const SET_DOC_DESCRIPTION = "SET_DOC_DESCRIPTION";
export const SET_DOC_SHIPMENT_REFERENCE = "SET_DOC_SHIPMENT_REFERENCE";

export const SET_PACK_DESCRIPTION = "SET_PACK_DESCRIPTION";
export const SET_PACK_SHIPMENT_REFERENCE = "SET_PACK_SHIPMENT_REFERENCE";
export const SET_PACK_SHIPMENT_PURPOSE = "SET_PACK_SHIPMENT_PURPOSE";

export const NEXT_ON_CREATE_SHIP_DETAILS = "NEXT_ON_CREATE_SHIP_DETAILS";
export const CLEAR_CREATE_SHIP_DETAILS = "CLEAR_CREATE_SHIP_DETAILS";
